version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
    timezone: Europe/Paris
  assignees:
  - simonsampere
  ignore:
  - dependency-name: lxml
    versions:
    - 4.6.2
  - dependency-name: pytest
    versions:
    - 6.2.1
  - dependency-name: docxtpl
    versions:
    - 0.11.2
